### ISSUE TITLE
[Bug] java.lang.StackOverFlowError: Ticking entity

### ISSUE THREAD

**Issue by Vineykmine** [TeamMoegMC/TheWinterRescue#100]
### Error Behaviour

This is only possible on a server on which you are both running Forge and are able to run Plugins on. You need this modpack installed and EssentialsX. If you get shot by a skeleton or attacked by any mob, your server crashes.
[crash-2024-10-30_23.27.50-server.txt](https://github.com/user-attachments/files/17579824/crash-2024-10-30_23.27.50-server.txt)

### Expected Behaviour

I enter server, kill the skeleton that tried to shoot me. Get on with my day.

### Reproduce

1. Ensure you are on a server capable of playing with both Forge and Plugins, in this case Mohist 1.16.5 build 1205.
2. Ensure the mods and config files are in the correct location. (I.E. Config inside the Config file. Mods inside the predetermined mods folder. Etc.)
3. Play the server atleast once after all is installed.
4. Go to the plugins tab and install EssentialsX and Vault. (Spigot versions)
5. Restart the server.
6. Play on the server and make sure it is dark outside.
7. Get attacked by any mob.
8. Server crash.

### Modpack version

0.5.6-rc2-hf7

### Server version

Mohist build 1205

### Other mods and plugins

EssentialsX-2.201.1.jar (plugin)
Vault.jar (plugin)
quickhomes-1.16.5-1.3.0-forge.jar (mod)

**Comment by yuesha-yc** [comment]
We can't support plugins unfortunately because we are a forge mod.
