### ISSUE TITLE
[Suggestion] Add right click harvest ability for crops

### ISSUE THREAD

**Issue by DYstebo** [TeamMoegMC/TheWinterRescue#102]
### Pain Point

Destroying crops, finding the seeds, planting the seeds. 
Takes a long time.

### Suggestion

Add a mod that would allow for easier planting and managing of crops, which would allow for harvesting and replanting with a single right click.

### Exsiting Mods

RightClickHarvest, Simple Harvest, or Gentle Harvest.

### Modpack version

0.5.6

**Comment by yuesha-yc** [comment]
Not something really necessary. We modify the crops system to fit our temperature system, so this may conflict.
