### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by deniselit08** [TeamMoegMC/TheWinterRescue#103]
### Pain Point

The modpack has delighted me based on what I've played so far; I mean, I have no issues at all

### Suggestion

I would simply like you to add an RPC for Discord so that the modpack we are playing shows up on our Discord profile. It may seem trivial, but it would be nice

### Exsiting Mods

Yes, there is only one on CurseForge for version 1.16.5, it’s [Simple Discord RPC](https://www.curseforge.com/minecraft/mc-mods/simple-discord-rpc)

### Modpack version

0.5.6.-rc2-hf7

**Comment by yuesha-yc** [comment]
I added it to recommended client mods. The design philosophy of the pack is to only add mods that are necessary to gameplay.
