### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by kekkyashi** [TeamMoegMC/TheWinterRescue#24]
### Error Behaviour

While attempting to play the multiplayer version of this modpack, we found that the quest book appears to be completely empty when we play. None of the quest lines show at all in the server despite them showing just fine in singleplayer. I have remade the server multiple times, even trying on an older version, and despite following all the steps to create the server the quest book does not show anything in it still.

### Expected Behaviour

Quest book should display the quest lines in multiplayer/server.

### Reproduce

1. downloaded the appropriate server version + client version
2. followed the steps in order to create a server
3. joined server to check quest book and quest to see that it is completely empty

### Modpack version

0.4.7 and 0.4.6

### Server version

0.4.7 and 0.4.6

**Comment by khjxiaogu** [comment]
Please, I beg you, DONT JUST COPY ALL MODS. Other folder MATTERS

**Comment by khjxiaogu** [comment]
Also, use our serverstarter instead of making server on your own, if you don't know how to make everything right.
