### ISSUE TITLE
[Bug] en_us translation not working on quest button

### ISSUE THREAD

**Issue by LetterN** [TeamMoegMC/TheWinterRescue#25]
### Error Behaviour

Missing / Wrong translation key for quest `Personal Stuff` and other checkbox ones (button ID `2128950991D0C6FA`)

![image](https://user-images.githubusercontent.com/24603524/147905707-6fd85a97-2ed6-48fa-8154-e6d361b1ceb8.png)

Checking around the translation files, it seems to exist but it isn't being used?

### Expected Behaviour

English translation for the text (en_us)

### Reproduce

1. Start new world
2. Check quest tree

### Modpack version

0.4.7-rc2

**Comment by khjxiaogu** [comment]
Fixed, would release shortly
