### ISSUE TITLE
[Bug] Creosoted sawdust briquette recipe doesn't work with IE's creosote 

### ISSUE THREAD

**Issue by LeoBeliik** [TeamMoegMC/TheWinterRescue#30]
### Error Behaviour

trying to craft the creosoted sawdust on a barrel with Immersive engineering creosote won't work, it needs charcoal pit's creosote specifically

![2022-02-10_04 44 05](https://user-images.githubusercontent.com/11804768/153361501-563df0cf-c9e4-4c54-9031-1b794497078c.png)

![2022-02-10_04 44 10](https://user-images.githubusercontent.com/11804768/153361518-0ad63c36-8017-4fdc-b58a-9d0d1423e764.png)

### Expected Behaviour

being able to create the item with any kind of creosote

### Reproduce

put IE creosote in a barrel
put 8 sawdust
contemplate

### Modpack version

0.4.7-stable2.2

**Comment by khjxiaogu** [comment]
That is intended
