### ISSUE TITLE
[Bug] [0.4.7-stable2.2][Multiplayer Server] Issue list

### ISSUE THREAD

**Issue by Elvarion** [TeamMoegMC/TheWinterRescue#32]
### Error Behaviour

Following all the steps to install the server;

- FTB Quest Config folder not being created correct. So to get quests we had to copy that folder from the client
- Flint Knife: Not getting Snowy wines when breaking leaves with it
- Cant place Snowy wines into drying rack

Not sure about more since after having to give ourself wines just to try and progress we gave up sadly.

### Expected Behaviour

Quests working out of the box
Flint Knife giving Wines
Wines being able to be dried

### Reproduce

Start server > Quests missing
Try and use Flint Knife on Leaves > Wines not dropping
Try and use Wines on Drying Rack > Not being placed

### Modpack version

0.4.7-stable2.2

### Server version

forge-1.16.5-36.2.4

**Comment by khjxiaogu** [comment]
You should install server with serverstarter. Don't install yourself.
