### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by 1172791203** [TeamMoegMC/TheWinterRescue#34]
### Question

Don't you want to continue updating?

### Modpack version

0.4.7

**Comment by IdrisQe** [comment]
Give them time. If you check the commit history, there has been work done since the last release, and both before and after your question. A heavily-customized modpack is fairly convoluted to work on, especially if the developers are busy with other things.

**Comment by yuesha-yc** [comment]
> Give them time. If you check the commit history, there has been work done since the last release, and both before and after your question. A heavily-customized modpack is fairly convoluted to work on, especially if the developers are busy with other things.

Pretty true. There will be release once the devs get into summer vacation

**Comment by yuesha-yc** [comment]
Close since 0.5
