### ISSUE TITLE
[Suggestion] Deployer has a bug while breaking drawers

### ISSUE THREAD

**Issue by Tollainmear** [TeamMoegMC/TheWinterRescue#36]
### Pain Point

That bug will duplicate the drawer and the content within,  it could be easly reproduced by placing like this:

![image](https://user-images.githubusercontent.com/25898067/168151221-7171c7c1-90ea-460f-8c85-945091a6a89f.png)

I've tride to fix it by using kubejs, that's works for me.
```
onEvent('block.break', event =>{
    if(event.block.id.contains("storagedrawers") && event.getEntity().getName() == "Deployer"){
        event.cancel()
    }
})
```

Btw, I havn't report this `feature` to neither create nor drawer's author, although it's seems that the bug is none of your bussiness, by holding a fiery heart, I hope this suggestion could make TWR better!

### Suggestion

the biggist wish is release newer modpack version quickly plz!

folks can't wait anylonger!

but I guess that hope might can't be met, so try to reproduce this bug at your convenience.

credits if there would be:
Tollainmear 
CN_Chitu

Nice work and best wishes! 

### Exsiting Mods

no more

### Modpack version

0.4.7

**Comment by khjxiaogu** [comment]
Fixed, thank you for advice!
