### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by Cyorageeee** [TeamMoegMC/TheWinterRescue#40]
### Question

When playing on a multiplayer server, when the cryolite bucket is put into the electrolytic tank, the electrolytic tank will disappear directly; at the same time, the secondary energy tower will also disappear in the server.

### Additional message

This all works fine in single player, I'm not sure if they are bugs.

### Related mods

Preset mods in mod packs.

### Modpack version

0.4.7

**Comment by yuesha-yc** [comment]
Update to latest
