### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by sossololpipi** [TeamMoegMC/TheWinterRescue#51]
### Error Behaviour

Evaporite does not act as "raw" stone (forge:stone) within recipes - only being purposeful in the creation of salt.
To mention is also the lack of any tags suitable for sedimentary stone.

### Expected Behaviour

Evaporite having the forge:stone tag

### Reproduce

1. jei
2. attempts to use evaporite as any other stone
3. failure

### Modpack version

0.5.2-rc1

**Comment by khjxiaogu** [comment]
That is intended, it is well known that salt can't be use as stones.
