### ISSUE TITLE
[Suggestion] Change translation format to use lists

### ISSUE THREAD

**Issue by Kodey-Kayla** [TeamMoegMC/TheWinterRescue#54]
### Pain Point

The translation files use a different translation key per new line. this makes adding new lines require updating all other files, or using \n and sacrificing readability.

### Suggestion

Add a feature to the translation function to allow using a list of strings where each entry is a new line. this would preserve readability in the translation files by allowing each list item to be displayed on a new line as well.

For example, "Bad news about the weather" I would like to change from:

> Bad news about the weather
> --------------------------
> There is not much time left
> 
> You found the weather radar in the inventory.
> It's connected to weather satellites in orbit.
> Because you now have lost the communication with the satellite, now radar can only be used in &climited time&f. Unless you can find a ground base station to re-establish the link with the satellite. You remember them as &bwhite domed buildings&f.
> Radar will forecast the weather for the next few days &bon the top of your screen&f
> About a day later, a &bviolent cold current&b will approach the landing site.
> Tempreture decreased a lot, a &cblizzard&f is incoming.
> Until then, an &benclosed&f shelter must be found and built.
> Your clothes won't protect you from the cold in a blizzard, so be sure to setup a &ecampfire&f.

to something more like 

> Bad News about the Weather
> --------------------------
> There is not much time left.
> 
> 
> Inside the cabin lies a small weather radar. 
> Usually, it would be connected through your ship to a network of weather satellites in orbit,
> and could receive forecasts about the weather from them.
> 
> However, without the support of your ship it has lost communication with most of these satellites. 
> Without a full connection the radar can only be used for &short term&f forecasts, 
> unless you can find another way to re-establish a connection with the satellites.
> 
> You remember earth having it's own weather outposts that were capable of providing this connection. 
> They looked a bit like like &bwhite dome-shaped buildings&f.
> 
> For the time being, your radar will be able to display the weather forecast for the next few days &bat the top of your screen&f.
> The forecast currently shows that in about a day's time, a &bviolent cold front&b will approach the crash site, 
> causing the temperature to decrease dramatically. A &cblizzard&f is incoming!
> 
> To prepare yourself, an &benclosed&f shelter should be found or constructed.
> Your spacesuit won't protect you from the cold in a blizzard, so be sure to create a &ecampfire&f to keep yourself warm.

Changes such as these are very impractical with the current system, as you can see I must add many new lines.

### Modpack version

0.5.3-rch4-hf5

**Comment by khjxiaogu** [comment]
FTBQuests does not support, And it is quite a lot work to make it support. Just edit quest and we use scripts to handle that is much easier
