### ISSUE TITLE
[Bug] game crash in achievement screen 

### ISSUE THREAD

**Issue by iAdoly** [TeamMoegMC/TheWinterRescue#55]
### Error Behaviour

the game crash when i open Tetra achievement 

### Expected Behaviour

to not crash and veiw achievement

### Reproduce

1 open achievement screen 
2 click on Tetra achievement Tab
3 game crash

### Modpack version

0.5.3-rc4-hf5

### Other mods and plugins

1- Magnesium
     someoneelsewastaken
     magnesium-1.5.jar

2-  Magnesium/Rubidium Dynamic Lights
      TeamDeusVult
       dynamiclightsreforged-mc1.16.5_v1.0.1.jar

3-  Magnesium/Rubidium Extras
      TeamDeusVult
       magnesium_extras-mc1.16.5_v1.4.0.jar

**Comment by iAdoly** [comment]
i fixed it with changing  magnesium-1.5.jar to rubidium-0.2.10.jar

**Comment by yuesha-yc** [comment]
Close it as we never officially support these mods. Use at your own risk.
