### ISSUE TITLE
[Bug] "Repurposing the energy core" description in the research table is too long

### ISSUE THREAD

**Issue by xieve** [TeamMoegMC/TheWinterRescue#57]
### Error Behaviour

![image](https://user-images.githubusercontent.com/20223093/206464008-500b3549-0a19-420d-b008-553fec128f49.png)
Image 1
![image](https://user-images.githubusercontent.com/20223093/206464162-dbfcdcf5-f907-478d-953d-b81259a98cec.png)
Image 2: Slightly scrolled down the entire dialog contents/both panes (why can I do that _and_ scroll the right pane alone?)

Seems like at least one line is missing here. My UI scale is 2, but I don't think that's relevant. I can't scroll down on the left pane, only on the right.

### Expected Behaviour

The text should not be clipping – either I should be able to scroll or the text should be shorter to fit inside the pane.

### Reproduce

1. Acquire Research Table
2. Open "Repurposing the energy core"

### Modpack version

0.5.5-rc1-hf1

### Server version

Forge Server 1.16.5-36.2.39

### Other mods and plugins

- Controlling
- StepUp
- Better Mods Button
- Dynamic Lights for Rubidium
- Rubidium
- Rubidium Extras
- Oculus
- Inventory Profiles Next (deactivated on this screen)
- Searchable Chests
- Xaero's Minimap
- Xaero's Worldmap
- Just Zoom
- Light Overlay

These are all client-only and they should not affect this UI

**Comment by gedeknepper** [comment]
I can reproduce this for several different research entries.

**Comment by khjxiaogu** [comment]
Confirmed, would be fixed in next release.  
Thanks for your feedback.
