### ISSUE TITLE
Rose bushes are useless

### ISSUE THREAD

**Issue by Thepigcat76** [TeamMoegMC/TheWinterRescue#61]
### Error Behaviour

Although rose bushes have a plant oil stat they cannot be eaten or used in the crock or stew pot

### Expected Behaviour

I think the player should be able to use the rose bush in stew pot and crock pot recipes

### Reproduce

Try to put the rose bush in the stew or crock pot. It will not work.

### Modpack version

0.5.4

**Comment by khjxiaogu** [comment]
That's intended. They are made for future use.
