### ISSUE TITLE
Tetra axes not honed by tree cutting

### ISSUE THREAD

**Issue by Corfiot** [TeamMoegMC/TheWinterRescue#62]
### Error Behaviour

 Since tetra axes almost always do mass tree block chopping, honing them becomes very very slow. And there's a lot of chopping in this pack :-)

### Expected Behaviour

chop tree, get honing points

### Reproduce

Go up to tree, use tetra axe to chop it down from root block. No honing experience is added to tool.

### Modpack version

0.5.5-stable1-hf1

**Comment by khjxiaogu** [comment]
This is a compatibility issue and have no way to be fixed.
