### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by generalforlife** [TeamMoegMC/TheWinterRescue#63]
### Error Behaviour

can make iron core spade without researching the geology tech.

### Expected Behaviour

should be tied to the tech

### Reproduce

in tetra table take a shovel and replace the head for core spade

### Modpack version

0.5.5-stablehf1

### Server version

official server

**Comment by khjxiaogu** [comment]
Generally you can, but making one by this way is much more expensive than making a brand new one with proper tech. But I would record this suggestion and consider further
