### ISSUE TITLE
[Suggestion] Update the server files!!

### ISSUE THREAD

**Issue by botkay** [TeamMoegMC/TheWinterRescue#66]
### Pain Point

there are outdated server files, so please update them!!

### Suggestion

please update the server files, it'll help me and my friends very much.

### Modpack version

0.5.5 stable1 hf1

**Comment by khjxiaogu** [comment]
Sorry, we won't provide serverpacks anymore as curseforge disabled 3-rd party downloads. But you can build up a server in less than 5 minutes with the tutorial on curseforge mainpage.
