### ISSUE TITLE
[Bug] Mixin冲突

### ISSUE THREAD

**Issue by SyuKoshiishi** [TeamMoegMC/TheWinterRescue#67]
### Error Behaviour

当服务器加入SpongeForge时服务器开不了，应该是FrostedHeart模组和SpongeForge的mixins冲突

### Expected Behaviour

不crash

### Reproduce

1、服务器端加入SpongeForge
2、crash

### Crash Report

https://gist.github.com/SyuKoshiishi/65e4a4fcb5ba51c1e9be00aab4ed6e37

### Modpack version

0.4.7

### Server version

Forge Server 36.2.5

### Other mods and plugins

SpongeForge 1.16.5-36.2.5-8.1.0-RC1312

**Comment by khjxiaogu** [comment]
自行安装其它模组和插件遇到问题请自行处理，我们不具备处理非整合包内容兼容性的能力。
