### ISSUE TITLE
Some documentation for the prospecting tools would help.

### ISSUE THREAD

**Issue by MerrittK** [TeamMoegMC/TheWinterRescue#9]
At first I assumed that the core shovel worked like the prospecting pick from terrafirmacraft where it scanned in a radius, but I quickly discovered that the core shovel scanned forward in a straight direction.

While I figured it out after a bit of trial and error, It might be easier for less experienced players if the scan type was explained in the questbook or tooltip.

**Comment by MerrittK** [comment]
I love the modpack. I hope my feedback isn't disheartening.

**Comment by yuesha-yc** [comment]
Actually this is already considered by our team.  Thanks for feedback and no worries TeamMoeg will always hear the voice of players who genuine play our work.

**Comment by yuesha-yc** [comment]
Actually this is already considered by our team.  Thanks for feedback and no worries TeamMoeg will always hear the voice of players who genuine play our work.
