### ISSUE TITLE
[Suggestion] Update map mod

### ISSUE THREAD

**Issue by DYstebo** [TeamMoegMC/TheWinterRescue#97]
### Pain Point

Map is basic, sometimes misleading with biome information, and hard to quickly create waypoints.

### Suggestion

Replace map mod with something that integrates well with existing features like ftb chunk claiming.

### Exsiting Mods

JourneyMap

### Modpack version

0.5.6

**Comment by yuesha-yc** [comment]
We invite you to add it yourself as you please. We design modpack to be as lightweight as possible.
